wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1686379175.297728
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      3:
      - 2
      - 23
      4: 3.10.0
      5: 0.15.4
      6: 4.29.2
      8:
      - 1
      - 4
      - 5
